
#!/usr/bin/env python3
"""
Study G/H: Options EPD/HIP Suite.
Formalizes the Options Validation (Pinning + Intraday Flow).

Method:
1. Run Market-Wide Validation (Pilot Run) to get Pinning/HIP metrics for 12 symbols.
2. Run HIP Null Test (Permutation) for GME to establish significance.
3. Consolidate into a summary report.
"""

import subprocess
import json
import pandas as pd
import os
from pathlib import Path

def run_command(cmd):
    print(f"Running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)

def main():
    base_dir = Path(__file__).resolve().parent.parent
    scripts_dir = base_dir / "scripts"

    # 1. Run Market-Wide Validation (Pilot Run) regarding Pinning and HIP
    script_pin = scripts_dir / "run_pinning_robustness.py"
    script_hip = scripts_dir / "run_hip_panel.py"

    run_command(["python3", str(script_pin)])
    run_command(["python3", str(script_hip)])
    
    # 2. Consolidate Results (Manual consolidation for now as scripts generate separate reports)
    # We will read the JSONs generated by the sub-scripts
    
    # 3. Generate Report
    out_dir = base_dir / "output"
    pin_json = out_dir / "pinning_robustness.md" # actually it makes an md
    # But let's check what run_pinning actually makes. It prints df. It saves md.
    # run_hip_panel makes json and md.
    
    hip_json = out_dir / "hip_panel_summary.json"
    
    # This orchestrator seems redundant if individual scripts produce reports.
    # But let's create a combined summary if possible, or just exit.
    
    out_md = out_dir / "options_suite_summary.md"
    with open(out_md, "w") as f:
        f.write("# Study G/H: Options EPD/HIP Suite\n\n")
        f.write("## Execution Summary\n")
        f.write(f"Executed `run_pinning_robustness.py` and `run_hip_panel.py`.\n")
        f.write(f"See `pinning_robustness.md` and `hip_panel_summary.md` in `{out_dir}` for details.\n")

if __name__ == "__main__":
    main()

if __name__ == "__main__":
    main()
